# Generated by Django 5.2.4 on 2026-04-07 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='productoption',
            unique_together={('product', 'option')},
        ),
        migrations.AddField(
            model_name='option',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.optiongroup'),
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='value',
        ),
    ]
