# Generated by Django 5.2.4 on 2026-04-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_producttopping_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttopping',
            name='image',
        ),
        migrations.AddField(
            model_name='topping',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='topping/'),
        ),
    ]
