# Generated by Django 5.2.4 on 2026-04-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_producttopping_image_topping_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
