# Generated by Django 5.2.4 on 2026-04-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_option_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='toppings/'),
        ),
    ]
