# Generated by Django 5.2.4 on 2026-04-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_optiongroup_created_at_optiongroup_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiongroup',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20),
        ),
    ]
