# Generated by Django 5.2.4 on 2026-04-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_topping_created_at_topping_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
