# Generated by Django 5.2.4 on 2026-04-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_category_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiongroup',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
