# Generated by Django 5.2.4 on 2026-04-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_deleted_at_order_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('momo', 'MoMo'), ('vnpay', 'VNPay'), ('zalopay', 'ZaloPay')], default='momo', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
