# Generated by Django 5.2.4 on 2026-04-27 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment_method_alter_order_deleted_at'),
        ('vouchers', '0002_voucher_created_at_voucher_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='voucher',
        ),
        migrations.CreateModel(
            name='OrderVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_vouchers', to='orders.order')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vouchers.voucher')),
            ],
        ),
    ]
