# Generated by Django 5.2.4 on 2026-04-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_voucher_created_at_voucher_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('order', 'Order Discount'), ('shipping', 'Shipping Discount')], default='order', max_length=20),
        ),
    ]
