# Generated by Django 5.2.4 on 2026-04-10 10:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_created_by_store_updated_at_store_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='StoreModel',
        ),
    ]
