# Generated by Django 5.2.4 on 2026-04-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='parsed_data',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='response_text',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='role',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='session_id',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='draft_order',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('confirming', 'Confirming'), ('order', 'Order'), ('modify', 'Modify')], default='idle', max_length=20),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
