# Generated by Django 5.2.4 on 2026-05-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0002_remove_chatmessage_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecache',
            name='response_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
